name: Deploy to Cloudflare Pages

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl pkg-config libssl-dev build-essential
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source $HOME/.cargo/env
        cargo install wasm-pack
        npm install -g wrangler

    - name: Build WASM
      working-directory: wasm
      run: wasm-pack build --release --target web

    - name: Install Node.js dependencies
      run: npm ci

    - name: Run build script
      run: npm run build

    - name: Authenticate Wrangler
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      run: wrangler whoami

    - name: Publish to Cloudflare Pages
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      run: wrangler pages deploy ./dist --project-name dtekv
