name: Deploy to Cloudflare Pages

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    environment: deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: "latest"

      - name: Build WASM
        working-directory: wasm
        run: wasm-pack build --release

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run build script
        run: npm run build

      - name: Authenticate Wrangler
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: wrangler whoami

      - name: Publish to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: wrangler pages deploy ./dist --project-name dtekv
